import { defineCatalog } from "@json-render/core";
import { schema } from "@json-render/react";
import { z } from "zod";

const kpiItemSchema = z.object({
  label: z.string(),
  value: z.string(),
  delta: z.string().nullable().optional(),
});

const linePointSchema = z.object({
  label: z.string(),
  value: z.number(),
});

const barPointSchema = z.object({
  label: z.string(),
  value: z.number(),
  delta: z.number().nullable().optional(),
});

export const jsonRenderDemoCatalog = defineCatalog(schema, {
  components: {
    DashboardPanel: {
      props: z.object({
        title: z.string(),
        subtitle: z.string(),
        asOf: z.string(),
      }),
      description: "Container for dashboard content with heading metadata.",
    },
    KpiStrip: {
      props: z.object({
        items: z.array(kpiItemSchema),
      }),
      description: "Horizontal KPI list used for quick numeric summaries.",
    },
    LineChartCard: {
      props: z.object({
        title: z.string(),
        yLabel: z.string(),
        points: z.array(linePointSchema),
      }),
      description: "Line chart card for trend data over time.",
    },
    BarChartCard: {
      props: z.object({
        title: z.string(),
        yLabel: z.string(),
        bars: z.array(barPointSchema),
      }),
      description: "Bar chart card for cross-entity comparisons.",
    },
    DataTableCard: {
      props: z.object({
        title: z.string(),
        columns: z.array(z.string()),
        rows: z.array(z.array(z.string())),
      }),
      description: "Tabular data card with simple columns and rows.",
    },
    InsightCard: {
      props: z.object({
        title: z.string(),
        text: z.string(),
      }),
      description: "Narrative insight block generated by the agent.",
    },
    FollowupsCard: {
      props: z.object({
        items: z.array(z.string()),
      }),
      description: "Suggested follow-up prompts.",
    },
  },
  actions: {},
});
